# Generated by Django 5.2.5 on 2025-12-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_pedido_notificacion_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12),
            preserve_default=False,
        ),
    ]
