# Generated by Django 5.2.5 on 2025-12-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12),
            preserve_default=False,
        ),
    ]
